trigger:
- main

pool: Default

variables:
  buildConfiguration: 'Release'
  
steps:
- script: # script path or inline
  workingDirectory: Booking.Server/
  displayName: Set working directory

- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true # Required for preview versions



- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit' 
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'PipelineArtifact'

  
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'BuildArtifact'