trigger:
- main

pool: Default

variables:
  buildConfiguration: 'Release'
  
steps:
- script: # script path or inline
  workingDirectory: Booking.Server/
  displayName: Set working directory

- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true # Required for preview versions



- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      Booking.Server/Booking.Server.DB/bin/**/*
      Booking.Server/Booking.Server.API/bin/**/*
      Booking.Server/Booking.Server.Test/bin/**/*

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: artifacts
  displayName: 'Publish artifact'