name: booking-api-test-build-artifacts

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: Booking.Server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set .NET version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger trx --results-directory "artifact"
    - name: Publish_1 
       run: dotnet publish "./Booking.Server.API/Booking.Server.API.csproj" -c release -o /app --no-restore
    - name: Publish_2
       run: dotnet publish "./Booking.Server.DB/Booking.Server.DB.csproj" -c release -o /app --no-restore
    - name: Publish_3
      run:  dotnet publish "./Booking.Server.Test/Booking.Server.Test.csproj" -c release -o /app --no-restore
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: catalog-api-artifact
          path: |
              /app/Booking.Server.DB.dll
              /app/Booking.Server.API.dll
              /app/Booking.Server.Test.dll
              
