name: Build

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: Booking.Server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set .NET version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger trx --results-directory "artifact"
    - name: Upload test logs
      uses: actions/upload-artifact@v3
      with:
            name: artifact
            path: Booking.Server/artifact
