name: booking-api-test-build-artifacts

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: Booking.Server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set .NET version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger trx --results-directory "artifact"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: catalog-api-artifact
          path: |
              Booking.Server.DB/bin/Debug/net6.0/Booking.Server.DB.dll
              Booking.Server.API/bin/Debug/net6.0/Booking.Server.API.dll
              Booking.Server.Test/bin/Debug/net6.0/Booking.Server.Test.dll
              
