name: booking-api-test-build-artifacts

on:
  pull_request:
    paths-ignore:
      - 'scripts/**'
      - 'middleware/**'

defaults:
  run:
    working-directory: Booking.Server

jobs:
  build:

    runs-on: self-hosted
    #changed to delf hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set .NET version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger trx --results-directory "artifact"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: catalog-api-artifact
          path: |
              ./Booking.Server/Booking.Server.DB/bin/
              ./Booking.Server/Booking.Server.API/bin/
              ./Booking.Server/Booking.Server.Test/bin/
              
